name: CampusWall
options:
  bundleIdPrefix: com.yourname
targets:
  CampusWall:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources: [CampusWall]
    settings:
      INFOPLIST_KEY_LSRequiresIPhoneOS: true
      INFOPLIST_KEY_UILaunchStoryboardName: LaunchScreen
      
