name: CampusWall
options:
  bundleIdPrefix: com.yourname
targets:
  CampusWall:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - path: .
        includes: ["*.swift", "*.storyboard", "Info.plist"] # 显式包含 Info.plist
    settings:
      GENERATE_INFOPLIST_FILE: NO # 告诉 Xcode 我们自己提供 Info.plist
      INFOPLIST_FILE: Info.plist
